version: '3.1'

services:
  # app:
  #   build: .
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - .:/app
  #   links:
  #     - db
  #   depends_on:
  #     - db

  db:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - .docker/data/db:/data/db
      - .docker/data/configdb:/data/configdb
      - .docker/data/dump:/data/dump